#!/usr/bin/env python3
"""Record what the REFERENCE engine decides, so VoiceAIKit can be held to it.

Five contracts, each one a place the two runtimes have already diverged or could
diverge without anything failing:

  1. fire_boundary   the confidence gate, on both sides of it
  2. interrupt       a new intent mid-slot-flow — VIK-050 lived here, with the
                     pack saying 0.68 and Swift hardcoding 0.75
  3. oov_guard       out-of-vocabulary refusal — VIK-054, Python-only until
                     recently, and the reason "help me find a paper" fired
  4. slot_budget     consecutive failed slot answers before the flow is abandoned
                     — VIK-053, three independent hardcoded 3s
  5. confirmation    which intents confirm before acting

WHY A FIXTURE AND NOT TWO TEST SUITES. Two suites written independently agree
only until someone changes one of them. A fixture generated from the reference
and consumed by the other runtime is the only shape that fails when they drift —
which is the entire point. `TopicDerivationParityTests` exists because that test
did NOT exist when `strippingDateTime` was written, and 8 of 20 utterances
diverged with nothing failing.

Never hand-edit the output. A hand-written expectation records what someone
BELIEVED the reference does, and this file exists because that belief has been
wrong repeatedly.

Usage:
    PYTHONPATH=packages/runtime python -m scripts.ci.emit_parity_fixtures \
        --lang en --out <VoiceAIKit>/Tests/VoiceAIKitTests/Fixtures/parity_expectations.json

Requires the trained artifacts (model.onnx + labels.pkl + weights) — it runs the
real engine, on purpose. A stub would record the stub's opinions.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

# Probes. Chosen to sit AROUND each boundary rather than comfortably inside it —
# a probe at 0.99 proves nothing about a 0.70 gate. The expected values are not
# written here; the reference decides them and this script records what it said.
PROBES = {
    "fire_boundary": [
        "turn up the volume",
        "increase the volume",
        "turn it up its too quiet",
        "set a reminder to take my pills",
        "what is the weather in bangalore tomorrow",
        "mmm hmm okay so",
    ],
    "interrupt": [
        # Said while a slot flow is awaiting an answer. The question is whether
        # the reference abandons the flow for the new intent or treats the words
        # as the answer.
        "increase the volume",
        "turn it up",
        "cancel that",
        "my hearing aids",
    ],
    "oov_guard": [
        "send a message to john",          # entity value: OOV by nature, real
        "stream from netflix",             # entity value: OOV by nature, real
        "help me find a paper",            # foreign topic: out of scope
        "turn off toshiba",
        "increase the volume",             # nothing unknown
    ],
    "slot_budget": [
        # Non-answers to an awaited slot, repeated until the reference gives up.
        "purple monkey dishwasher",
    ],
}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--lang", default="en")
    ap.add_argument("--out", type=Path, required=True)
    a = ap.parse_args(argv)

    sys.path.insert(0, str(REPO / "packages" / "runtime"))
    from nlu_engine.engine import NLUEngine          # noqa: E402

    engine = NLUEngine()
    schema = engine.schema

    out: dict = {
        "_note": (
            "GENERATED by scripts/ci/emit_parity_fixtures.py from the reference "
            "engine. Regenerate, never hand-edit — a hand-written expectation "
            "records a belief, and this file exists because the belief was wrong."
        ),
        "_lang": a.lang,
        # Recorded so a stale fixture is visible rather than silently compared
        # against a pack that has since been retuned.
        "thresholds": {
            "confidence": engine.threshold,
            "interrupt": engine.interrupt_threshold,
            "agreement": engine.agreement_threshold,
            "oov_reject": schema.get("oov_reject_ratio"),
            "oov_bypass": schema.get("oov_bypass_confidence"),
            "max_slot_attempts": engine.max_slot_attempts,
        },
    }

    # --- 1. fire boundary --------------------------------------------------
    fire = []
    for text in PROBES["fire_boundary"]:
        engine.reset("parity-fire")
        r = engine.handle("parity-fire", text)
        fire.append({"text": text, "type": r.type, "intent": r.intent,
                     "confidence": round(float(r.confidence), 6)})
    out["fire_boundary"] = fire

    # --- 3. oov guard ------------------------------------------------------
    # Ratio is recorded separately from the verdict: the ratio is what Swift's
    # `PackTFIDFVectorizer.oovRatio` must reproduce exactly, and the verdict is
    # what the engine does with it. A test that only checks the verdict cannot
    # tell a tokenizer bug from a threshold bug.
    oov = []
    for text in PROBES["oov_guard"]:
        engine.reset("parity-oov")
        r = engine.handle("parity-oov", text)
        oov.append({"text": text,
                    "oov_ratio": round(float(engine.classifier.oov_ratio(text)), 6),
                    "type": r.type, "intent": r.intent,
                    "confidence": round(float(r.confidence), 6)})
    out["oov_guard"] = oov

    # --- 5. confirmation policy -------------------------------------------
    # Straight off the content, no model needed — but recorded here so the whole
    # contract lives in one file the Swift side reads once.
    #
    # Derived exactly as `content_bundle.compile_policies` does: `always` for an
    # intent that declares a `followup`, `never` for every other one. There is no
    # `when_ambiguous` — that band was removed, not retuned (103 friction turns
    # against 16 useful catches), and the compiler deliberately never emits it.
    # Deriving it here the same way means a change to that rule breaks this
    # fixture, which is the point.
    out["confirmation"] = sorted(
        ({"intent": name,
          "policy": "always" if cfg.get("followup") else "never"}
         for name, cfg in schema["intents"].items()),
        key=lambda e: e["intent"])

    # --- 2 & 4 are DIALOGUE contracts -------------------------------------
    # They need a driven session rather than one utterance, so they record the
    # SEQUENCE and the reference's verdict at each step.
    interrupts = []
    for text in PROBES["interrupt"]:
        engine.reset("parity-int")
        engine.handle("parity-int", "set a reminder")   # opens a slot flow
        r = engine.handle("parity-int", text)
        interrupts.append({"text": text, "type": r.type, "intent": r.intent,
                           "confidence": round(float(r.confidence), 6),
                           "interrupted": r.interrupted_intent})
    out["interrupt"] = interrupts

    budget = []
    for text in PROBES["slot_budget"]:
        engine.reset("parity-slot")
        engine.handle("parity-slot", "set a reminder")
        steps = []
        for turn in range(engine.max_slot_attempts + 1):
            r = engine.handle("parity-slot", text)
            steps.append({"turn": turn + 1, "type": r.type, "intent": r.intent})
        budget.append({"text": text, "steps": steps})
    out["slot_budget"] = budget

    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text(json.dumps(out, indent=1, sort_keys=False) + "\n",
                     encoding="utf-8")
    print(f"wrote {a.out}")
    for k, v in out.items():
        if isinstance(v, list):
            print(f"  {k:16s} {len(v)} cases")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
