#!/usr/bin/env python3
"""
Post-Distillation Deployment Script
===================================
Takes the raw, 90 MB PyTorch FP32 model generated by the Google Colab
distillation script, performs broad vocabulary pruning, and exports it
to a highly optimized INT8 ONNX file (~9 MB).
"""

import os
import sys
import json
import torch
import shutil
import pandas as pd
from pathlib import Path
from transformers import AutoModel, AutoTokenizer

BASE_DIR = Path(__file__).resolve().parents[2]

# --- Configuration ---
INPUT_MODEL_DIR = Path(__file__).parent / "stage2_contrastive_bge_small_l3"
OUTPUT_DIR = Path(__file__).parent / "output_models" / "stage2_contrastive_bge_small_onnx"
TRAIN_CSV_PATH = BASE_DIR / "language_packs" / "en" / "train.csv"
OOS_CSV_PATH = BASE_DIR / "language_packs" / "en" / "extras" / "oos_2.csv"
MAX_VOCAB_SIZE = 10000


def get_broad_vocabulary(tokenizer):
    """
    Builds a broad vocabulary of exactly MAX_VOCAB_SIZE tokens.
    Prioritizes:
    1. Special tokens ([CLS], [SEP], [PAD], [UNK], [MASK])
    2. All subwords found in our domain data (train.csv and oos_2.csv)
    3. The most common generic English subwords from the base model
       until the quota is met.
    """
    print("1. Building Broad Vocabulary...")
    vocab = tokenizer.get_vocab()

    # 1. Special tokens
    special_tokens = set(["[PAD]", "[UNK]", "[CLS]", "[SEP]", "[MASK]"])
    retained_tokens = set(special_tokens)

    # 2. Domain Data
    texts = []
    if TRAIN_CSV_PATH.exists():
        df_train = pd.read_csv(TRAIN_CSV_PATH)
        texts.extend(df_train["text"].astype(str).tolist())
    if OOS_CSV_PATH.exists():
        df_oos = pd.read_csv(OOS_CSV_PATH)
        texts.extend(df_oos["text"].astype(str).tolist())

    domain_tokens = set()
    for text in texts:
        tokens = tokenizer.tokenize(str(text))
        domain_tokens.update(tokens)

    print(f"   Found {len(domain_tokens)} unique subwords in domain data.")
    retained_tokens.update(domain_tokens)

    # Ensure all retained tokens actually exist in the base vocab
    retained_tokens = {t for t in retained_tokens if t in vocab}

    # 3. Fill the rest with common tokens (assuming base vocab is ordered by frequency roughly, or we just take the first N)
    sorted_base_tokens = sorted(vocab.items(), key=lambda x: x[1])
    for token, idx in sorted_base_tokens:
        if len(retained_tokens) >= MAX_VOCAB_SIZE:
            break
        retained_tokens.add(token)

    print(f"   Final retained vocabulary size: {len(retained_tokens)} tokens.")

    # Create the new mapping
    new_vocab = {}
    tokens_to_keep_indices = []

    # Assign new IDs starting from 0, preserving [PAD]=0, [UNK]=100 if possible, but for ONNX it doesn't matter
    # as long as the tokenizer.json is updated. We will just sort them by original ID to keep it simple.
    original_indices = [vocab[t] for t in retained_tokens]
    original_indices.sort()

    for new_idx, old_idx in enumerate(original_indices):
        token = sorted_base_tokens[old_idx][0]
        new_vocab[token] = new_idx
        tokens_to_keep_indices.append(old_idx)

    return new_vocab, tokens_to_keep_indices


def prune_model(model, tokens_to_keep_indices):
    """Slices the embedding matrix of the PyTorch model."""
    print("2. Slicing Model Embedding Matrix...")
    embeddings = model.embeddings.word_embeddings
    old_weight = embeddings.weight.data

    new_weight = old_weight[tokens_to_keep_indices, :]

    new_embeddings = torch.nn.Embedding(len(tokens_to_keep_indices), old_weight.shape[1])
    new_embeddings.weight.data = new_weight

    model.embeddings.word_embeddings = new_embeddings
    model.config.vocab_size = len(tokens_to_keep_indices)

    print(f"   Original embedding shape: {old_weight.shape}")
    print(f"   New embedding shape:      {new_weight.shape}")
    return model


def export_to_onnx(model, tokenizer, output_dir):
    print("\n3. Exporting to ONNX and Quantizing...")
    from optimum.onnxruntime import ORTModelForFeatureExtraction, ORTQuantizer
    from optimum.onnxruntime.configuration import AutoQuantizationConfig

    # Save a temporary PyTorch version
    temp_pt_dir = output_dir / "temp_pt"
    model.save_pretrained(temp_pt_dir)
    tokenizer.save_pretrained(temp_pt_dir)

    # Export to ONNX via optimum
    ort_model = ORTModelForFeatureExtraction.from_pretrained(temp_pt_dir, export=True)

    # Quantize using Optimum's config (which handles Embeddings correctly)
    quantizer = ORTQuantizer.from_pretrained(ort_model)
    qconfig = AutoQuantizationConfig.avx512_vnni(is_static=False, per_channel=False)

    quantizer.quantize(save_dir=str(output_dir), quantization_config=qconfig)

    shutil.rmtree(temp_pt_dir, ignore_errors=True)

    quantized_onnx_path = output_dir / "model_quantized.onnx"
    if quantized_onnx_path.exists():
        print(
            f"   Exported quantized ONNX to {quantized_onnx_path} ({quantized_onnx_path.stat().st_size / 1024 / 1024:.2f} MB)"
        )


def update_tokenizer(tokenizer, new_vocab, output_dir):
    """Updates the fast tokenizer JSON file with the new vocabulary."""
    print("5. Updating Fast Tokenizer...")

    # Save the tokenizer files so we get tokenizer.json
    tokenizer.save_pretrained(output_dir)

    tok_json_path = output_dir / "tokenizer.json"
    if tok_json_path.exists():
        with open(tok_json_path, "r", encoding="utf-8") as f:
            tok_data = json.load(f)

        # Update the main vocab
        tok_data["model"]["vocab"] = new_vocab

        with open(tok_json_path, "w", encoding="utf-8") as f:
            json.dump(tok_data, f, ensure_ascii=False)

    print("   Tokenizer updated.")


def main():
    if not INPUT_MODEL_DIR.exists():
        print(f"ERROR: Could not find downloaded model at {INPUT_MODEL_DIR}")
        print("Make sure you unzipped the Colab output into this directory!")
        sys.exit(1)

    print(f"Loading raw PyTorch model from {INPUT_MODEL_DIR}")

    # Load the distilled model (it's a SentenceTransformer, but we only need the base AutoModel for ONNX)
    model = AutoModel.from_pretrained(INPUT_MODEL_DIR)
    tokenizer = AutoTokenizer.from_pretrained(INPUT_MODEL_DIR)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    new_vocab, tokens_to_keep_indices = get_broad_vocabulary(tokenizer)

    model = prune_model(model, tokens_to_keep_indices)

    export_to_onnx(model, tokenizer, OUTPUT_DIR)

    update_tokenizer(tokenizer, new_vocab, OUTPUT_DIR)

    print(f"\n🎉 DONE! Your final ~9 MB model is ready at: {OUTPUT_DIR}/model_quantized.onnx")


if __name__ == "__main__":
    main()
