#!/usr/bin/env python3
"""
Interactive testing script to compare embeddings generated by the Baseline,
Track 1 (Pruned L3), and Track 3 (SVD L6) models on custom user input.
"""

import sys
import time
import numpy as np
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(BASE_DIR))

from artifact import ArtifactContractError, encode, head_path, load_encoder

MODELS = {
    "Track 1 (Pruned L3)": Path(__file__).parent
    / "output_models"
    / "track1_pruned_l3"
    / "onnx_quantized"
    / "model_quantized.onnx",
    "Track 3 (SVD L6)": Path(__file__).parent
    / "output_models"
    / "track3_svd_l6"
    / "onnx_quantized"
    / "model_quantized.onnx",
    "Track 1 (Stage 1 Distilled)": Path(__file__).parent
    / "output_models"
    / "final_distilled_onnx"
    / "model_quantized.onnx",
    "Track 1 (Stage 2 Contrastive)": Path(__file__).parent
    / "output_models"
    / "stage2_contrastive_onnx"
    / "model_quantized.onnx",
}


def cosine_similarity(v1, v2):
    dot = np.dot(v1, v2)
    norm = np.linalg.norm(v1) * np.linalg.norm(v2)
    if norm == 0:
        return 0.0
    return dot / norm


import pickle


def main():
    print("Loading models... Please wait.")
    encoders = {}
    classifiers = {}

    for name, path in MODELS.items():
        if not path.exists():
            print(f"Skipping {name} (File not found: {path})")
            continue

        try:
            encoders[name] = load_encoder(path)

            clf_path = head_path(path)
            if clf_path.exists():
                with open(clf_path, "rb") as f:
                    classifiers[name] = pickle.load(f)

            encode(encoders[name], ["warmup"])
            print(
                f"✅ {encoders[name].summary()}"
                + ("  (with Classifier)" if name in classifiers else "")
            )
        except ArtifactContractError as exc:
            print(f"❌ {name}: artifact contract not satisfied\n     {exc}")
        except Exception as e:
            print(f"❌ Failed to load {name}: {e}")

    if not encoders:
        print("No models loaded. Exiting.")
        return

    print("\n" + "=" * 50)
    print("Semantic Compression Interactive Tester")
    print("Type any sentence to generate embeddings. Type 'exit' or 'quit' to stop.")
    print("=" * 50 + "\n")

    while True:
        try:
            user_input = input("\nEnter a sentence: ").strip()
            if not user_input:
                continue
            if user_input.lower() in ["exit", "quit"]:
                break

            print(f"\nProcessing: '{user_input}'")
            print("-" * 50)

            results = {}
            for name in encoders.keys():
                t0 = time.time()
                vec = encode(encoders[name], [user_input])[0]
                t1 = time.time()
                latency_ms = (t1 - t0) * 1000
                results[name] = vec

                vec_slice = ", ".join([f"{x:+.4f}" for x in vec[:4]])

                print(f"[{name}]")
                print(f"  Latency    : {latency_ms:.2f} ms")
                print(f"  Vector     : [{vec_slice} ...]")

                if name in classifiers:
                    clf = classifiers[name]
                    probs = clf.predict_proba([vec])[0]
                    best_idx = np.argmax(probs)
                    intent = clf.classes_[best_idx]
                    confidence = probs[best_idx]
                    print(f"  Intent     : {intent} (Confidence: {confidence*100:.1f}%)")

                reference = next(iter(results))
                if name != reference:
                    sim = cosine_similarity(results[reference], vec)
                    print(f"  Similarity : {sim*100:.1f}% match to {reference}")
                print()

        except KeyboardInterrupt:
            break
        except Exception as e:
            print(f"\nError processing input: {e}")

    print("\nExiting. Goodbye!")


if __name__ == "__main__":
    main()
