#!/usr/bin/env python3
"""
Interactive testing script to compare embeddings generated by the Baseline,
Track 1 (Pruned L3), and Track 3 (SVD L6) models on custom user input.
"""

import sys
import time
import numpy as np
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(BASE_DIR))

from transformers import AutoTokenizer
from packages.runtime.nlu_engine.inference import OrtEmbedderBackend

MODELS = {
    "Baseline": BASE_DIR / "models" / "minilm-l6-v2.onnx",
    "Track 1 (Pruned L3)": Path(__file__).parent
    / "output_models"
    / "track1_pruned_l3"
    / "onnx_quantized"
    / "model_quantized.onnx",
    "Track 3 (SVD L6)": Path(__file__).parent
    / "output_models"
    / "track3_svd_l6"
    / "onnx_quantized"
    / "model_quantized.onnx",
    "Track 1 (Stage 1 Distilled)": Path(__file__).parent
    / "output_models"
    / "final_distilled_onnx"
    / "model_quantized.onnx",
    "Track 1 (Stage 2 Contrastive)": Path(__file__).parent
    / "output_models"
    / "stage2_contrastive_onnx"
    / "model_quantized.onnx",
}


def cosine_similarity(v1, v2):
    dot = np.dot(v1, v2)
    norm = np.linalg.norm(v1) * np.linalg.norm(v2)
    if norm == 0:
        return 0.0
    return dot / norm


def embed_onnx(backend, text, tokenizer):
    encoded = tokenizer(
        text, max_length=64, truncation=True, padding="max_length", return_tensors="np"
    )
    input_ids = encoded["input_ids"]
    # Clamp out of bounds IDs due to fast tokenizer mismatch with pruned matrix
    input_ids[input_ids >= 10000] = 100
    attention_mask = encoded["attention_mask"]
    token_type_ids = encoded.get("token_type_ids", np.zeros_like(input_ids))

    token_embeddings = backend.embed_tokens(input_ids, attention_mask, token_type_ids)

    if backend.model_path.name == "minilm-l6-v2.onnx":
        mask = attention_mask[0]
        expanded = mask[:, np.newaxis].astype(np.float32)
        summed = (token_embeddings * expanded).sum(axis=0)
        vec = summed / expanded.sum()
    else:
        vec = token_embeddings[0]

    norm = np.linalg.norm(vec)
    if norm > 0:
        vec = vec / norm
    return vec


import pickle


def main():
    print("Loading models... Please wait.")
    backends = {}
    tokenizers = {}
    classifiers = {}

    for name, path in MODELS.items():
        if not path.exists():
            print(f"Skipping {name} (File not found: {path})")
            continue

        try:
            tokenizer_path = path.parent.parent / "pytorch"
            if not tokenizer_path.exists():
                tokenizer_path = "sentence-transformers/all-MiniLM-L6-v2"

            tokenizers[name] = AutoTokenizer.from_pretrained(tokenizer_path)
            backends[name] = OrtEmbedderBackend(path)

            clf_path = path.parent.parent / "classifier_head.pkl"
            if clf_path.exists():
                with open(clf_path, "rb") as f:
                    classifiers[name] = pickle.load(f)

            # Warmup
            embed_onnx(backends[name], "warmup", tokenizers[name])
            print(f"✅ Loaded {name}" + (" (with Classifier)" if name in classifiers else ""))
        except Exception as e:
            print(f"❌ Failed to load {name}: {e}")

    if not backends:
        print("No models loaded. Exiting.")
        return

    print("\n" + "=" * 50)
    print("Semantic Compression Interactive Tester")
    print("Type any sentence to generate embeddings. Type 'exit' or 'quit' to stop.")
    print("=" * 50 + "\n")

    while True:
        try:
            user_input = input("\nEnter a sentence: ").strip()
            if not user_input:
                continue
            if user_input.lower() in ["exit", "quit"]:
                break

            print(f"\nProcessing: '{user_input}'")
            print("-" * 50)

            results = {}
            for name in backends.keys():
                t0 = time.time()
                vec = embed_onnx(backends[name], user_input, tokenizers[name])
                t1 = time.time()
                latency_ms = (t1 - t0) * 1000
                results[name] = vec

                vec_slice = ", ".join([f"{x:+.4f}" for x in vec[:4]])

                print(f"[{name}]")
                print(f"  Latency    : {latency_ms:.2f} ms")
                print(f"  Vector     : [{vec_slice} ...]")

                if name in classifiers:
                    clf = classifiers[name]
                    probs = clf.predict_proba([vec])[0]
                    best_idx = np.argmax(probs)
                    intent = clf.classes_[best_idx]
                    confidence = probs[best_idx]
                    print(f"  Intent     : {intent} (Confidence: {confidence*100:.1f}%)")

                if name != "Baseline" and "Baseline" in results:
                    sim = cosine_similarity(results["Baseline"], vec)
                    print(f"  Similarity : {sim*100:.1f}% match to Baseline")
                print()

        except KeyboardInterrupt:
            break
        except Exception as e:
            print(f"\nError processing input: {e}")

    print("\nExiting. Goodbye!")


if __name__ == "__main__":
    main()
