#!/usr/bin/env python3
"""
Test Distilled Model on Honest Holdout Set
==========================================
Evaluates the final 9 MB Stage 2 Contrastive distilled ONNX model and its
Logistic Regression classifier head against the purely unseen holdout dataset
(`language_packs/en/holdout_honest.csv`).
"""

import sys
import time
import pickle
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import accuracy_score, classification_report, f1_score

from artifact import encode, head_path, load_encoder

HERE = Path(__file__).parent

# --- Inside this directory --------------------------------------------------
DISTILLED_MODEL_PATH = (
    HERE / "output_models" / "stage2_contrastive_bge_small_onnx" / "model_quantized.onnx"
)
DISTILLED_CLF_PATH = head_path(DISTILLED_MODEL_PATH)

# --- Outside this directory -------------------------------------------------
# Evaluation data and the incumbent model this one has to beat. Everything
# below is an INPUT: lifting this directory into another project means
# repointing these, and the run degrades gracefully when they are absent
# rather than failing. No code is imported from outside this directory.
REPO_ROOT = Path(__file__).resolve().parents[2]
HOLDOUT_CSV_PATH = REPO_ROOT / "language_packs" / "en" / "holdout_honest.csv"
TFIDF_MODEL_PATH = REPO_ROOT / "models" / "intent" / "en" / "model.onnx"
TFIDF_LABELS_PATH = REPO_ROOT / "models" / "intent" / "en" / "labels.json"


REPORT_PATH = Path(__file__).parent / "holdout_results.md"
RESULTS = []


def evaluate_model(name, true_labels, predictions, total_time, n_samples, detail=""):
    print(f"\n==================================================")
    print(f"Holdout Evaluation Results: {name}")
    print(f"==================================================")

    acc = accuracy_score(true_labels, predictions)
    f1 = f1_score(true_labels, predictions, average="macro", zero_division=0)

    print(f"Total Test Phrases : {n_samples}")
    print(f"Overall Accuracy   : {acc:.4f}")
    print(f"Macro-F1 Score     : {f1:.4f}")
    print(f"Total Latency      : {total_time:.2f}s ({(total_time/n_samples)*1000:.2f} ms/query)")
    print(f"==================================================\n")

    RESULTS.append(
        {
            "model": name,
            "detail": detail,
            "accuracy": acc,
            "macro_f1": f1,
            "ms_per_query": (total_time / n_samples) * 1000,
        }
    )


def write_report(n_samples, holdout_name):
    """Write the numbers down.

    Four encoders and two GPU sessions produced no recorded measurement in this
    repository, which is why the accuracy of the 9 MB model had to be
    re-derived from scratch months later. A run that does not leave a committed
    artifact behind did not happen.
    """
    lines = [
        "# Holdout evaluation",
        "",
        f"Generated by `{Path(__file__).name}`.",
        "",
        f"- Holdout: `{holdout_name}` ({n_samples} rows)",
        f"- Encoder: `{DISTILLED_MODEL_PATH.relative_to(HERE)}`",
        f"- Head: `{DISTILLED_CLF_PATH.relative_to(HERE)}`",
        "",
        "> `holdout_honest.csv` is 44% near-duplicate of `train.csv` by token",
        "> Jaccard. These numbers measure reproducibility of the artifact, not",
        "> semantic quality. See `docs/Prod-Work-Documentation/semantic_compression_plan.md` §4.",
        "",
        "| Model | Detail | Accuracy | Macro-F1 | ms/query |",
        "|---|---|---:|---:|---:|",
    ]
    for r in RESULTS:
        lines.append(
            f"| {r['model']} | {r['detail']} | {r['accuracy']:.4f} | "
            f"{r['macro_f1']:.4f} | {r['ms_per_query']:.2f} |"
        )
    lines.append("")
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Report written to {REPORT_PATH}")


def run_tfidf_baseline(texts, true_labels):
    """Score the shipping TF-IDF model on the same holdout, if it is present.

    Inlined rather than imported from packages.runtime so this directory keeps
    no code dependency on the rest of the repository. The graph takes a string
    tensor and emits (label, probabilities), so the label output is used
    directly. Optional on purpose: this comparison is context, not the subject
    of the test, and it must not stop the run when the model is not there.
    """
    if not (TFIDF_MODEL_PATH.exists() and TFIDF_LABELS_PATH.exists()):
        print(f"Skipping TF-IDF baseline: {TFIDF_MODEL_PATH} not found.\n")
        return

    import onnxruntime as ort

    print("Loading TF-IDF Baseline Model...")
    try:
        session = ort.InferenceSession(str(TFIDF_MODEL_PATH))
    except Exception as exc:
        # The graph carries a locale-dependent string normaliser, which is not
        # present on every platform. Context, not the subject -- keep going.
        print(f"Skipping TF-IDF baseline: {type(exc).__name__}: {str(exc)[:120]}\n")
        return

    input_name = session.get_inputs()[0].name

    print("Evaluating TF-IDF Model...")
    predictions = []
    start_time = time.time()
    for text in texts:
        label = session.run(None, {input_name: np.array([[text]])})[0]
        predictions.append(str(label[0]))
    elapsed = time.time() - start_time

    evaluate_model(
        "TF-IDF (shipping)",
        true_labels,
        predictions,
        elapsed,
        len(texts),
        detail=f"{TFIDF_MODEL_PATH.stat().st_size / 1024 / 1024:.2f} MB",
    )


def main():
    if not HOLDOUT_CSV_PATH.exists():
        print(f"❌ Error: Holdout dataset not found at {HOLDOUT_CSV_PATH}")
        sys.exit(1)

    print(f"Loading Holdout Dataset: {HOLDOUT_CSV_PATH.name}")
    df = pd.read_csv(HOLDOUT_CSV_PATH, encoding="utf-8-sig")
    df.columns = [c.strip().lower() for c in df.columns]
    df["text"] = df["text"].astype(str).str.lower().str.strip()
    df["intent"] = df["intent"].astype(str).str.strip()

    texts = df["text"].tolist()
    true_labels = df["intent"].tolist()
    print(f"Loaded {len(texts)} test phrases.\n")

    # ---------------------------------------------------------
    # 1. The incumbent, for context -- skipped when it is not reachable
    # ---------------------------------------------------------
    run_tfidf_baseline(texts, true_labels)

    # ---------------------------------------------------------
    # 2. Distilled Semantic Model Evaluation
    # ---------------------------------------------------------
    # Tokenizer, pooling, id-range and head all come from the artifact itself.
    print(f"Loading distilled encoder: {DISTILLED_MODEL_PATH.relative_to(HERE)}")
    encoder = load_encoder(DISTILLED_MODEL_PATH)
    print(f"  {encoder.summary()}")
    print(f"  head: {DISTILLED_CLF_PATH.relative_to(HERE)}")
    with open(DISTILLED_CLF_PATH, "rb") as f:
        clf = pickle.load(f)

    print("Evaluating Distilled Model...")
    start_time = time.time()

    X = []
    batch_size = 500
    for i in range(0, len(texts), batch_size):
        X.append(encode(encoder, texts[i : i + batch_size]))

    X = np.vstack(X)
    probs = clf.predict_proba(X)
    distilled_predictions = [clf.classes_[np.argmax(p)] for p in probs]
    distilled_time = time.time() - start_time

    evaluate_model(
        encoder.name,
        true_labels,
        distilled_predictions,
        distilled_time,
        len(texts),
        detail=(
            f"{encoder.size_mb:.2f} MB, {encoder.layers} layers, pooling {encoder.pooling}, "
            f"vocab {encoder.vocab_size}, from {encoder.source or 'unrecorded'}"
        ),
    )

    write_report(len(texts), HOLDOUT_CSV_PATH.name)


if __name__ == "__main__":
    main()
