"""Capability source tree ⇄ compiled schema (ADR-002 A4, ADR-005 Part 4).

The SOURCE form teams edit lives in ``content/capabilities/<id>/``:

    capability.yaml            id, status, languages, intent list
    intents/<leaf>.yaml        full intent config (canonical/en)
    prompts/{fr,de,da}.yaml    per-intent localized overrides

Platform-owned, order-sensitive tables stay in ``content/platform.yaml`` (+
per-language ``platform.<lang>.yaml``): thresholds, keyword_triggers (an
ORDERED pre-filter list — first match wins, so it is deliberately NOT split
per capability; ADR-005 ships keywords as a top-level bundle file too),
yes/no lexicons, polarity guards, uncertainty-confirm config.

The COMPILED form the engine actually loads remains
``content/nlu_schema.json`` + ``content/localization/nlu_schema.*.json`` —
regenerated by :func:`assemble` and proven identical by the round-trip test
(tests/test_content_source.py), which is also the CI drift guard: edit the
source tree, run ``python -m nlu_compiler.content_source assemble``, commit
both.

Capability ownership comes from docs/Review-F5/capability-map.json (§A3).
"""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
CONTENT = REPO / "content"
CAP_DIR = CONTENT / "capabilities"
CAP_MAP = REPO / "docs" / "Review-F5" / "capability-map.json"
SCHEMA = CONTENT / "nlu_schema.json"
LOC = CONTENT / "localization"
LANGS = ("fr", "de", "da")

# Top-level schema keys owned by the platform (not any capability).
PLATFORM_KEYS = ("version", "confidence_threshold", "slot_confidence_threshold",
                 "interrupt_threshold",
                 "semantic_threshold", "semantic_rescue_enabled",
                 "keyword_triggers", "affirmative", "negative",
                 "polarity_guards", "help_marker_guard", "uncertain_confirm")


def _yaml():
    import yaml
    return yaml


def _dump(path: Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_yaml().safe_dump(data, sort_keys=True, allow_unicode=True,
                                      width=100), encoding="utf-8")


def _load(path: Path):
    return _yaml().safe_load(path.read_text(encoding="utf-8"))


def intent_to_capability() -> dict[str, str]:
    cap = json.loads(CAP_MAP.read_text())
    return {e["proposed_intent"]: e["capability"]
            for e in cap["intents"].values() if e["proposed_intent"]}


def split() -> dict:
    """One-time decomposition of the compiled schema into the source tree."""
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    overlays = {lang: json.loads((LOC / f"nlu_schema.{lang}.json").read_text(encoding="utf-8"))
                for lang in LANGS}
    owner = intent_to_capability()

    caps: dict[str, list[str]] = {}
    for intent in schema["intents"]:
        caps.setdefault(owner[intent], []).append(intent)

    for cap_id, intents in sorted(caps.items()):
        base = CAP_DIR / cap_id
        _dump(base / "capability.yaml", {
            "id": cap_id, "status": "active",
            "languages": ["en", *LANGS],
            "intents": sorted(intents),
        })
        for intent in intents:
            _dump(base / "intents" / f"{intent}.yaml",
                  {"intent": intent, **schema["intents"][intent]})
        for lang in LANGS:
            per_lang = {i: overlays[lang]["intents"][i]
                        for i in intents if i in overlays[lang].get("intents", {})}
            if per_lang:
                _dump(base / "prompts" / f"{lang}.yaml", per_lang)

    _dump(CONTENT / "platform.yaml",
          {k: schema[k] for k in PLATFORM_KEYS if k in schema})
    for lang in LANGS:
        platform = {k: v for k, v in overlays[lang].items() if k != "intents"}
        _dump(CONTENT / f"platform.{lang}.yaml", platform)
    return {"capabilities": len(caps), "intents": sum(len(v) for v in caps.values())}


def assemble(write: bool = True) -> dict:
    """Rebuild the compiled schema files from the source tree.

    Returns {"schema": ..., "overlays": {lang: ...}}; writes them when
    ``write`` (the compiled files stay git-tracked — the engine and iOS load
    them directly; the drift test keeps them honest).
    """
    platform = _load(CONTENT / "platform.yaml")
    schema: dict = {k: platform[k] for k in PLATFORM_KEYS if k in platform}
    intents: dict = {}
    overlay_intents: dict[str, dict] = {lang: {} for lang in LANGS}

    for cap_yaml in sorted(CAP_DIR.glob("*/capability.yaml")):
        base = cap_yaml.parent
        cap = _load(cap_yaml)
        for intent in sorted(cap["intents"]):
            cfg = _load(base / "intents" / f"{intent}.yaml")
            assert cfg.pop("intent") == intent, f"{base}: intent key mismatch"
            intents[intent] = cfg
        for lang in LANGS:
            p = base / "prompts" / f"{lang}.yaml"
            if p.exists():
                overlay_intents[lang].update(_load(p))

    # Preserve the compiled files' key layout: platform keys in their
    # original position with intents where the current schema puts them.
    ordered = {}
    for key in ("version", "confidence_threshold", "slot_confidence_threshold",
                "interrupt_threshold",
                "semantic_threshold", "semantic_rescue_enabled", "keyword_triggers"):
        if key in schema:
            ordered[key] = schema[key]
    ordered["intents"] = intents
    for key in ("affirmative", "negative", "polarity_guards",
                "help_marker_guard", "uncertain_confirm"):
        if key in schema:
            ordered[key] = schema[key]
    # The layout above is a second, hand-maintained list of the same keys, so it
    # can silently drop a platform key that PLATFORM_KEYS accepts — which is
    # exactly what happened to `interrupt_threshold`: platform.yaml carried it,
    # PLATFORM_KEYS allowed it, and it never reached the compiled schema, so the
    # engine kept using its fallback. Fail loudly instead.
    dropped = sorted(set(schema) - set(ordered))
    assert not dropped, (
        f"platform key(s) {dropped} accepted by PLATFORM_KEYS but missing from "
        f"the compiled layout above — add them, or they are silently discarded")

    overlays = {}
    for lang in LANGS:
        plat = _load(CONTENT / f"platform.{lang}.yaml")
        overlay = {}
        if "_meta" in plat:
            overlay["_meta"] = plat["_meta"]
        for k, v in plat.items():
            if k != "_meta":
                overlay[k] = v
        overlay["intents"] = overlay_intents[lang]
        overlays[lang] = overlay

    if write:
        SCHEMA.write_text(json.dumps(ordered, indent=2, ensure_ascii=False) + "\n",
                          encoding="utf-8")
        for lang in LANGS:
            (LOC / f"nlu_schema.{lang}.json").write_text(
                json.dumps(overlays[lang], indent=2, ensure_ascii=False) + "\n",
                encoding="utf-8")
    return {"schema": ordered, "overlays": overlays}


def main(argv=None) -> int:
    import argparse

    ap = argparse.ArgumentParser(prog="nlu_compiler.content_source", description=__doc__)
    ap.add_argument("command", choices=["split", "assemble", "check"])
    args = ap.parse_args(argv)
    if args.command == "split":
        print(json.dumps(split()))
        return 0
    if args.command == "assemble":
        assemble(write=True)
        print("compiled schema files regenerated from content/capabilities/")
        return 0
    # check: assembled output must equal the tracked compiled files
    built = assemble(write=False)
    current = json.loads(SCHEMA.read_text(encoding="utf-8"))
    ok = built["schema"] == current
    for lang in LANGS:
        ok &= built["overlays"][lang] == json.loads(
            (LOC / f"nlu_schema.{lang}.json").read_text(encoding="utf-8"))
    print("in sync" if ok else "DRIFT: source tree and compiled schema disagree")
    return 0 if ok else 1


if __name__ == "__main__":
    import sys
    sys.exit(main())
