"""App-compatibility label shim (boundary-only).

The model and the whole training/eval pipeline speak the modern
``domain.object.action`` taxonomy (ND-3). Some downstream app builds still
expect the legacy Dialogflow label space (``Cmd.VolumeIncrease``, ``Help_*``,
``Default Fallback Intent``). Rather than reverting the model, we translate at
the single public boundary: ``NLUEngine.handle`` -> ``NLUResult``.

Nothing inside the engine, model, schema, lexicons, calibration or tests
changes. This maps ONLY the outward-facing label strings, and only when the
compat map is present. Delete the map (or set the env flag off) once the app
consumes the modern labels and this shim is a no-op.

Map source: ``legacy_label_map.json`` (new -> legacy), generated by inverting
``language_packs/en/extras/sources/label_migration_map.json``. Edit the map
VALUES if the app contract differs from the recorded legacy names (e.g.
camelCase ``cmd.volumeIncrease`` instead of ``Cmd.VolumeIncrease``).
"""

from __future__ import annotations

import json
import os
from functools import lru_cache
from pathlib import Path
from typing import Optional

_MAP_PATH = Path(__file__).with_name("legacy_label_map.json")

# Label-bearing fields on NLUResult that the app reads. Kept explicit so a new
# field can't silently ship a modern label to a legacy consumer.
_LABEL_FIELDS = ("intent", "interrupted_intent", "tfidf_intent")


@lru_cache(maxsize=1)
def _load() -> dict:
    """Full compat config. Empty => shim disabled (no-op).

    OFF by default (opt-in): the engine, model and test suite all speak the
    modern ``domain.object.action`` labels. Only an app deployment that needs
    the legacy Dialogflow contract sets ``NLU_LEGACY_LABELS=1`` to translate at
    the boundary. Keeping it off by default means internal callers and tests are
    never silently relabeled.
    """
    if os.environ.get("NLU_LEGACY_LABELS", "0") != "1":
        return {}
    if not _MAP_PATH.exists():
        return {}
    return json.loads(_MAP_PATH.read_text(encoding="utf-8"))


def _load_map() -> dict[str, str]:
    """new-label -> legacy-app-label."""
    return dict(_load().get("map", {}))


def to_app_label(label: Optional[str]) -> Optional[str]:
    """Translate one modern label to the legacy app label.

    Passthrough for None, for sentinels the app already knows (e.g. "GENAI"),
    and for anything not in the map — so an unmapped/new intent degrades to its
    modern name rather than being dropped.
    """
    if label is None:
        return None
    return _load_map().get(label, label)


def apply(result):
    """Rewrite the label-bearing fields on an NLUResult in place, return it.

    ONE pass: the simple rename, modern label -> legacy app label, on every
    label field. Passthrough for anything not in the map.

    It used to have a second pass. A resolved confirmation was tagged by the
    engine with ``_confirm_polarity`` + ``_confirmed_intent``, and this function
    looked the pair up in ``confirm_compound`` to override ``intent`` with
    ``Cmd.SendMessage - yes``. That is gone, and not because the behaviour
    changed — the compound name is still reported. It moved to where it belongs:
    the content authors it on the confirmation branch, beside that branch's
    action and text, and ``_handle_confirmation`` reads it there. One turn, one
    place, and the device gets the same string from the same source instead of
    from a separate artifact that had to be shipped and kept in step.

    Safe to call unconditionally: a missing/disabled map makes this a no-op.
    """
    m = _load_map()
    if not m:
        return result

    for name in _LABEL_FIELDS:
        val = getattr(result, name, None)
        if val is not None:
            setattr(result, name, m.get(val, val))
    return result
